local Color = require("Color")
local lovecase = require("libs.lovecase")

local expect = lovecase.expect
local suite = lovecase.newSuite("Color")

suite:describe("type()", function ()
  suite:test("should return the typename", function ()
    expect.equal("loveshape.Color", Color.new(1, 1, 1):type())
  end)
end)

suite:describe("new()", function ()
  suite:test("should create a color with the specified components", function ()
    expect.almostEqual({0.1, 0.2, 0.3, 0.4}, Color.new(0.1, 0.2, 0.3, 0.4))
  end)
  suite:test("should set alpha to 1 by default", function ()
    expect.almostEqual({0, 0, 0, 1}, Color.new(0, 0, 0))
  end)
  suite:test("should clamp components between 0 and 1", function ()
    expect.almostEqual({0, 1, 1, 0}, Color.new(-1, 255, 100, -100))
  end)
  suite:test("should accept a table argument", function ()
    expect.almostEqual({1, 1, 0, 1}, Color.new{1, 1, 0, 1})
  end)
end)

suite:describe("set()", function ()
  suite:test("should set the color components", function ()
    expect.almostEqual({0.1, 0.2, 0.3, 0.4}, Color.new(0, 0, 0):set(0.1, 0.2, 0.3, 0.4))
  end)
  suite:test("should set alpha to 1 by default", function ()
    expect.almostEqual({0, 0, 0, 1}, Color.new(0, 0, 0):set(0, 0, 0))
  end)
  suite:test("should clamp components between 0 and 1", function ()
    expect.almostEqual({0, 1, 1, 0}, Color.new(0, 0, 0):set(-1, 255, 100, -100))
  end)
  suite:test("should accept a table argument", function ()
    expect.almostEqual({1, 1, 0, 1}, Color.new(0, 0, 0):set{1, 1, 0, 1})
  end)
end)

suite:describe("unpack()", function ()
  suite:test("should return the color components", function ()
    expect.almostEqual({0.1, 0.2, 0.3, 0.4}, {Color.new(0.1, 0.2, 0.3, 0.4):unpack()})
  end)
end)

suite:describe("equal()", function ()
  suite:test("should return true if colors are equal", function ()
    local r, g, b, a = 1, 0.5, 0.75, 1
    local color1 = Color.new(r, g, b, a)
    local color2 = Color.new(r, g, b, a)
    expect.isTrue(color1:equal(color2))
    expect.isTrue(color1:equal(r, g, b, a))
  end)
  suite:test("should return false if colors are not equal", function ()
    local color1 = Color.new(0.25, 0.5, 1)
    local color2 = Color.new(1, 1, 1)
    expect.isFalse(color1:equal(color2))
    expect.isFalse(color1:equal(0, 0, 0))
  end)
end)

return suite
