local lovecase = require("libs.lovecase")
local Rectangle = require("Rectangle")
local Shape = require("Shape")

local expect = lovecase.expect
local suite = lovecase.newSuite("Shape")

--- @return loveshape.Shape
--- @nodiscard
--- @package
local function newShape()
  local shape = setmetatable({}, Shape)
  shape:_init(4)
  return shape
end

--- @param width number
--- @param height number
--- @return loveshape.Shape
--- @nodiscard
--- @package
local function newRectangleShape(width, height)
  -- Some tests cannot be performed by the abstract Shape class.
  -- For these cases we use a rectangle instead.
  return Rectangle.new(width, height)
end

suite:describe("type()", function ()
  suite:test("should return the typename", function ()
    expect.equal("loveshape.Shape", newShape():type())
  end)
end)

suite:describe("setFillColor()", function ()
  suite:test("should set the fill color", function ()
    local shape = newShape()
    shape:setFillColor(0.1, 0.2, 0.3, 0.4)
    expect.almostEqual({0.1, 0.2, 0.3, 0.4}, {shape:getFillColor()})
  end)
  suite:test("should accept a table argument", function ()
    local shape = newShape()
    shape:setFillColor({0.1, 0.2, 0.3, 0.4})
    expect.almostEqual({0.1, 0.2, 0.3, 0.4}, {shape:getFillColor()})
  end)
  suite:test("should clamp color components between 0 and 1", function ()
    local shape = newShape()
    shape:setFillColor(-1, 255, 200, -100)
    expect.almostEqual({0, 1, 1, 0}, {shape:getFillColor()})
  end)
end)

suite:describe("getFillColor()", function ()
  suite:test("should initially return opaque white", function ()
    local shape = newShape()
    expect.almostEqual({1, 1, 1, 1}, {shape:getFillColor()})
  end)
end)

suite:describe("setBorderColor()", function ()
  suite:test("should set the border color", function ()
    local shape = newShape()
    shape:setBorderColor(0.1, 0.2, 0.3, 0.4)
    expect.almostEqual({0.1, 0.2, 0.3, 0.4}, {shape:getBorderColor()})
  end)
  suite:test("should accept a table argument", function ()
    local shape = newShape()
    shape:setBorderColor({0.1, 0.2, 0.3, 0.4})
    expect.almostEqual({0.1, 0.2, 0.3, 0.4}, {shape:getBorderColor()})
  end)
  suite:test("should clamp color components between 0 and 1", function ()
    local shape = newShape()
    shape:setBorderColor(-1, 255, 200, -100)
    expect.almostEqual({0, 1, 1, 0}, {shape:getBorderColor()})
  end)
end)

suite:describe("getBorderColor()", function ()
  suite:test("should initially return opaque white", function ()
    local shape = newShape()
    expect.almostEqual({1, 1, 1, 1}, {shape:getBorderColor()})
  end)
end)

suite:describe("setBorderWidth()", function ()
  suite:test("should set the border width", function ()
    local shape = newShape():setBorderWidth(3)
    expect.equal(3, shape:getBorderWidth())
  end)
  suite:test("should disable soft edges", function ()
    local shape = newRectangleShape(100, 100):setEdgeSmoothing(10)
    shape:setBorderWidth(2)
    expect.equal(nil, shape:getEdgeMesh())
  end)
end)

suite:describe("getBorderWidth()", function ()
  suite:test("should initially return 0", function ()
    expect.equal(0, newShape():getBorderWidth())
  end)
end)

suite:describe("setBorderSmoothing()", function ()
  suite:test("should set the border smoothing", function ()
    local shape = newShape():setBorderSmoothing(3)
    expect.equal(3, shape:getBorderSmoothing())
  end)
  suite:test("should not accept negative values", function ()
    expect.error(function ()
      newShape():setBorderSmoothing(-1)
    end)
  end)
end)

suite:describe("getBorderSmoothing()", function ()
  suite:test("should initially return 1", function ()
    expect.equal(1, newShape():getBorderSmoothing())
  end)
end)

suite:describe("setEdgeSmoothing()", function ()
  suite:test("should set the edge smoothing", function ()
    local shape = newShape():setEdgeSmoothing(3)
    expect.equal(3, shape:getEdgeSmoothing())
  end)
  suite:test("should not accept negative values", function ()
    expect.error(function ()
      newShape():setEdgeSmoothing(-1)
    end)
  end)
end)

suite:describe("getEdgeSmoothing()", function ()
  suite:test("should initially return 1", function ()
    expect.equal(1, newShape():getEdgeSmoothing())
  end)
end)

suite:describe("getPointsCount()", function ()
  suite:test("should return the number of vertices", function ()
    expect.equal(4, newShape():getPointsCount())
  end)
end)

suite:describe("getBounds()", function ()
  suite:test("should get the bounding rectangle", function ()
    local rect = newRectangleShape(100, 200)
    expect.equal({0, 0, 100, 200}, {rect:getBounds()})
  end)
  suite:test("should include outer borders", function ()
    local rect = newRectangleShape(100, 200):setBorderWidth(10)
    expect.equal({-10, -10, 120, 220}, {rect:getBounds()})
  end)
  suite:test("should not include outer border smoothing", function ()
    local rect = newRectangleShape(100, 200):setBorderWidth(10):setBorderSmoothing(5)
    expect.equal({-10, -10, 120, 220}, {rect:getBounds()})
  end)
  suite:test("should include inner borders", function ()
    local rect = newRectangleShape(100, 200):setBorderWidth(-10)
    expect.equal({0, 0, 100, 200}, {rect:getBounds()})
  end)
  suite:test("should include inner border smoothing", function ()
    local rect = newRectangleShape(100, 200):setBorderWidth(-10):setBorderSmoothing(5)
    expect.equal({0, 0, 100, 200}, {rect:getBounds()})
  end)
  suite:test("should not include soft edges", function ()
    local rect = newRectangleShape(100, 200):setEdgeSmoothing(5)
    expect.equal({0, 0, 100, 200}, {rect:getBounds()})
  end)
end)

suite:describe("setTexture()", function ()
  local image = love.graphics.newImage("assets/wall.png")

  suite:test("should set the mesh texture", function ()
    local shape = newShape():setTexture(image)
    expect.same(image, shape:getTexture())
  end)
  suite:test("should optionally set the texture quad", function ()
    local shape = newShape()
    shape:setTexture(image)
    expect.equal({0, 0, 0, 0}, {shape:getTextureQuad()})
    shape:setTexture(image, true)
    expect.equal({0, 0, 256, 256}, {shape:getTextureQuad()})
  end)
end)

suite:describe("getTexture()", function ()
  suite:test("should initially return nil", function ()
    expect.equal(nil, newShape():getTexture())
  end)
end)

suite:describe("setTextureQuad()", function ()
  suite:test("should set the texture quad", function ()
    local shape = newShape():setTextureQuad(10, 20, 30, 40)
    expect.equal({10, 20, 30, 40}, {shape:getTextureQuad()})
  end)
end)

suite:describe("getTextureQuad()", function ()
  suite:test("should initially return an empty quad", function ()
    expect.equal({0, 0, 0, 0}, {newShape():getTextureQuad()})
  end)
end)

suite:describe("getBorderMesh()", function ()
  suite:test("should initially return nil", function ()
    expect.equal(nil, newRectangleShape(10, 10):getBorderMesh())
  end)
  suite:test("should return a mesh if a border is set", function ()
    local shape = newRectangleShape(10, 10):setBorderWidth(1)
    expect.equal("userdata", type(shape:getBorderMesh()))
  end)
end)

suite:describe("getEdgeMesh()", function ()
  suite:test("should initially return a mesh", function ()
    expect.equal("userdata", type(newRectangleShape(10, 10):getEdgeMesh()))
  end)
  suite:test("should return nil if soft edges are disabled", function ()
    local shape = newRectangleShape(10, 10):setEdgeSmoothing(0)
    expect.equal(nil, shape:getEdgeMesh())
  end)
end)

return suite